// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sicjzbxklxpftbqbsjap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpY2p6YnhrbHhwZnRicWJzamFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTY4MDEsImV4cCI6MjA1OTkzMjgwMX0.RFbqAR0W2Y4z5lNAkDpLcw20e5sdPQwhl6iyhNF7zvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);